const state={operator:null,orders:[],selected:null,queue:"active"};
const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const stageInfo={review_availability:["Confirmar disponibilidad","Controlá físicamente cantidades y faltantes.","info"],waiting_acceptance:["Esperar aceptación del cliente","Hubo cambios y el cliente debe aceptarlos.","warning"],waiting_payment:["Esperar aprobación administrativa","El pago o crédito todavía no está resuelto.","warning"],ready_to_prepare:["Iniciar preparación","Tomá el pedido e iniciá picking.","success"],preparing:["Completar preparación","Prepará, embalá y rotulá todos los bultos.","success"],awaiting_dispatch:["Registrar despacho o retiro","Entregá realmente el pedido y completá los datos.","progress"],in_transit:["Esperar recepción del cliente","El cliente ya fue informado del despacho.","done"]};
const unfulfilledReasons={finished_stock_shortage:"Falta de producto terminado",material_shortage:"Falta de insumos para fabricar",production_delay:"Producción demorada",discontinued:"Producto discontinuado",commercial_agreement:"Cantidad corregida por acuerdo comercial",order_error:"Error en el pedido",other:"Otro motivo"};
async function api(path,options={}){const body=Object.prototype.hasOwnProperty.call(options,"body");const r=await fetch(path,{credentials:"same-origin",...options,headers:body?{"content-type":"application/json",...(options.headers||{})}:options.headers,body:body?JSON.stringify(options.body):undefined});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"No se pudo completar la operación.");return p}
function toast(message){const n=$("#logisticsToast");n.textContent=message;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),2600)}
async function boot(){bind();try{const {operator}=await api("/api/logistics/me");enter(operator)}catch{}}
function bind(){
  $("#logisticsLoginForm").addEventListener("submit",login);$("#toggleLogisticsPassword").addEventListener("click",()=>{const i=$("#logisticsPassword");i.type=i.type==="password"?"text":"password";$("#toggleLogisticsPassword").textContent=i.type==="password"?"Ver":"Ocultar"});
  $("#reloadLogistics").addEventListener("click",load);$("#logisticsSearch").addEventListener("input",debounce(load,250));$("#logisticsStage").addEventListener("change",render);
  document.querySelectorAll("[data-queue]").forEach(button=>button.addEventListener("click",()=>setQueue(button.dataset.queue)));
  $("#logisticsOrders").addEventListener("click",e=>{const b=e.target.closest("[data-order]");if(b)openOrder(Number(b.dataset.order))});
  $("#logisticsDetail").addEventListener("click",handleDetailClick);$("#logisticsDetail").addEventListener("submit",handleDetailSubmit);
}
async function login(e){e.preventDefault();const m=$("#logisticsLoginMessage");m.textContent="";try{const {operator}=await api("/api/logistics/login",{method:"POST",body:Object.fromEntries(new FormData(e.currentTarget))});enter(operator)}catch(error){m.textContent=error.message}}
async function enter(operator){state.operator=operator;$("#logisticsLogin").classList.add("hidden");$("#logisticsWorkspace").classList.remove("hidden");$("#logisticsSession").innerHTML=`<strong>${esc(operator.name)}</strong> <button id="logisticsLogout">Salir</button>`;$("#logisticsLogout").onclick=logout;await load();const orderId=Number(new URLSearchParams(location.search).get("order")||0);if(orderId)await openOrder(orderId)}
async function logout(){await api("/api/logistics/logout",{method:"POST"});location.reload()}
async function load(){const q=$("#logisticsSearch").value.trim();const params=new URLSearchParams({scope:state.queue});if(q)params.set("q",q);const {orders}=await api(`/api/logistics/orders?${params}`);state.orders=orders;render()}
async function setQueue(queue){state.queue=queue==="dispatched"?"dispatched":"active";$("#logisticsStage").value="";document.querySelectorAll("[data-queue]").forEach(button=>button.classList.toggle("active",button.dataset.queue===state.queue));$("#logisticsStage").classList.toggle("hidden",state.queue==="dispatched");$("#logisticsSearch").placeholder=state.queue==="dispatched"?"Buscar entre los pedidos despachados":"Buscar pedido, cliente o CUIT";$("#logisticsDetail").classList.add("hidden");await load()}
function render(){const filter=$("#logisticsStage").value;const rows=state.orders.filter(o=>!filter||(filter==="waiting"?["waiting_acceptance","waiting_payment"].includes(o.stage):o.stage===filter));const counts={review_availability:0,waiting:0,ready_to_prepare:0,preparing:0,awaiting_dispatch:0};state.orders.forEach(o=>{const k=["waiting_acceptance","waiting_payment"].includes(o.stage)?"waiting":o.stage;if(k in counts)counts[k]++});$("#logisticsStats").classList.toggle("hidden",state.queue==="dispatched");$("#logisticsStats").innerHTML=Object.entries(counts).map(([k,v])=>`<div class="stat"><span>${esc(({review_availability:"Disponibilidad",waiting:"En espera",ready_to_prepare:"Para preparar",preparing:"Preparando",awaiting_dispatch:"Para despachar"})[k])}</span><strong>${v}</strong></div>`).join("");const empty=state.queue==="dispatched"?"No hay pedidos despachados para esta búsqueda.":"No hay pedidos con trabajo pendiente para este filtro.";$("#logisticsOrders").innerHTML=rows.length?rows.map(card).join(""):`<p>${empty}</p>`}
function card(o){const [title,body,tone]=stageInfo[o.stage]||["Revisar pedido","Abrí el detalle.","info"];return `<article class="order ${tone}"><div><strong>${esc(o.orderNumber)} · ${esc(o.businessName)}</strong><small>${o.operatorName?`Asignado a ${esc(o.operatorName)}`:"Sin operario asignado"}</small></div><div class="next"><span>PRÓXIMA ACCIÓN</span><strong>${esc(title)}</strong><small>${esc(body)}</small></div><button data-order="${o.id}">Ver pedido</button></article>`}
async function openOrder(id){const {order}=await api(`/api/logistics/orders/${id}`);state.selected=order;renderDetail();$("#logisticsDetail").classList.remove("hidden");$("#logisticsDetail").scrollIntoView({behavior:"smooth"})}
function renderDetail(){const o=state.selected;const row=state.orders.find(r=>r.id===o.id)||{};const stage=row.stage||detailStage(o);const [title,body]=stageInfo[stage]||["Revisar pedido",""];const assigned=o.logistics?.operatorId;const mine=Number(assigned||0)===Number(state.operator.id);let action="";
  if(stage==="review_availability")action=availabilityForm(o,mine,assigned);
  else if(stage==="ready_to_prepare"&&(!assigned||mine))action=`<button class="primary" data-claim>${assigned?"Iniciar preparación":"Tomar e iniciar preparación"}</button>`;
  else if(stage==="ready_to_prepare"&&!mine)action=`<p>Este pedido está asignado a otro operario.</p>`;
  else if(stage==="preparing"&&mine)action=checklistForm(o);
  else if(stage==="awaiting_dispatch")action=dispatchForm(o);
  else action=`<p>${esc(body)}</p>`;
  const packages=o.logistics?.packages||1;
  const documentsReady=Boolean(o.logistics?.packed);
  $("#logisticsDetail").innerHTML=`<div class="detail-head"><div><p class="eyebrow">${esc(o.orderNumber)}</p><h2>${esc(o.businessName)}</h2></div><button data-close>Cerrar</button></div><div class="action-banner"><strong>Próxima acción: ${esc(title)}</strong><p>${esc(body)}</p></div><div class="actions document-actions"><button data-doc="picking">1. Imprimir preparación</button><button data-doc="labels" ${documentsReady?"":"disabled"}>2. Generar ${packages} etiqueta${packages===1?"":"s"} A4</button><button data-doc="remit" ${documentsReady?"":"disabled"}>3. Generar remito</button></div>${documentsReady?"":`<p class="document-help">Para habilitar etiquetas y remito, marcá Embalado, ingresá la cantidad total de bultos y guardá el control.</p>`}<div class="items">${o.items.map(item=>`<div class="item"><strong>${esc(item.warehouseLocation||"Sin ubicación")}<br>${esc(item.kmCode)}</strong><span class="item-description">${esc(item.productName)}<small>Pedido: ${item.quantity} · Confirmado: ${item.confirmedQuantity||0}</small></span>${stage==="review_availability"?`<div class="availability-controls"><input form="availabilityForm" name="qty-${item.id}" type="number" min="0" max="${item.quantity}" value="${item.quantity}" /><select form="availabilityForm" name="reason-${item.id}" aria-label="Motivo de diferencia"><option value="">Motivo si hay diferencia</option>${Object.entries(unfulfilledReasons).map(([code,label])=>`<option value="${code}">${esc(label)}</option>`).join("")}</select><input form="availabilityForm" name="note-${item.id}" placeholder="Observación opcional" /></div>`:""}</div>`).join("")}</div>${action}`;
}
function availabilityForm(o,mine,assigned){if(assigned&&!mine)return `<p>Este control fue tomado por otro operario.</p>`;return `<form id="availabilityForm"><label>Nota general<textarea name="reason" rows="2"></textarea></label><button class="primary" type="submit" data-availability>Confirmar disponibilidad</button></form>`}
function checklistForm(o){const l=o.logistics||{};return `<form id="checklistForm"><div class="checklist"><label><input name="prepared" type="checkbox" ${l.prepared?"checked":""}/><span>Preparado</span></label><label><input name="packed" type="checkbox" ${l.packed?"checked":""}/><span>Embalado</span></label><label><input name="labeled" type="checkbox" ${l.labeled?"checked":""}/><span>Rotulado</span></label></div><label class="packages-field"><span>Cantidad total de bultos</span><input name="packages" type="number" min="1" max="99" value="${l.packages||1}" required /><small>Guardá esta cantidad antes de generar los documentos. El sistema hará una etiqueta A4 por cada bulto.</small></label><button class="primary" type="submit" data-checklist>Guardar control y cantidad de bultos</button></form>`}
function dispatchForm(o){return `<form id="dispatchForm"><div class="dispatch-grid"><label>Modalidad<select name="fulfillmentMethod" required><option value="">Seleccionar</option><option>Retira en local</option><option>Transporte</option><option>Expreso</option><option>Cadeteria</option><option>Entrega propia</option><option>Otro</option></select></label><label>Transporte o persona responsable<input name="fulfillmentCarrier" required /></label><label>Guía, remito o referencia<input name="fulfillmentTracking" /></label><label>Entrega o retiro estimado<input name="fulfillmentEstimatedDate" type="date" required /></label><label>Observaciones<textarea name="fulfillmentNotes"></textarea></label></div><button class="primary" type="submit" data-dispatch>Confirmar despacho y avisar al cliente</button></form>`}
async function handleDetailClick(e){if(e.target.closest("[data-close]"))return $("#logisticsDetail").classList.add("hidden");if(e.target.closest("[data-claim]")){await api(`/api/logistics/orders/${state.selected.id}/claim`,{method:"POST",body:{}});toast("Pedido asignado e iniciado.");await load();return openOrder(state.selected.id)}const doc=e.target.closest("[data-doc]");if(doc){const packages=Number(state.selected.logistics?.packages||0);if(doc.dataset.doc!=="picking"&&(!Number.isInteger(packages)||packages<1)){return toast("Ingresá y guardá la cantidad de bultos antes de generar documentos.")}const page=doc.dataset.doc==="picking"?"picking.html":doc.dataset.doc==="labels"?"labels.html":"shipping-remit.html";open(`/${page}?order=${state.selected.id}&packages=${packages}&source=logistics`,"_blank","noopener")}}
async function handleDetailSubmit(e){e.preventDefault();const f=e.target;if(f.id==="availabilityForm"){const items=state.selected.items.map(i=>({id:i.id,confirmedQuantity:Number(f.elements[`qty-${i.id}`].value),unfulfilledReasonCode:f.elements[`reason-${i.id}`].value||"",availabilityNote:f.elements[`note-${i.id}`].value||""}));await api(`/api/logistics/orders/${state.selected.id}/availability`,{method:"PATCH",body:{items,reason:new FormData(f).get("reason")||""}});toast("Disponibilidad confirmada.")}else if(f.id==="checklistForm"){await api(`/api/logistics/orders/${state.selected.id}/checklist`,{method:"PATCH",body:{prepared:f.elements.prepared.checked,packed:f.elements.packed.checked,labeled:f.elements.labeled.checked,packages:Number(f.elements.packages.value)}});toast("Control actualizado.")}else if(f.id==="dispatchForm"){await api(`/api/logistics/orders/${state.selected.id}/dispatch`,{method:"PATCH",body:Object.fromEntries(new FormData(f))});toast("Pedido despachado y cliente notificado. Se movió a Despachados.");state.selected=null;$("#logisticsDetail").classList.add("hidden");await load();return}await load();await openOrder(state.selected.id)}
function detailStage(o){if(o.fulfillment?.status==="shipped")return"in_transit";if(o.fulfillment?.status==="ready")return"awaiting_dispatch";if(o.status==="order_created"||o.adjustmentReviewRequestedAt)return"review_availability";if(o.modifiedAcceptanceRequired)return"waiting_acceptance";if(!["paid","credit_account","settled_adjustment"].includes(o.paymentStatus))return"waiting_payment";return o.logistics?.status==="preparing"?"preparing":"ready_to_prepare"}
function debounce(fn,ms){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),ms)}}boot();
