const state={operator:null,plan:null,reports:[],operators:[],products:[],draftId:null,extraProductsByDate:new Map(),reportDraftByDate:new Map()};
const $=(s)=>document.querySelector(s);const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const hasBody=Object.prototype.hasOwnProperty.call(options,"body");const response=await fetch(path,{credentials:"same-origin",...options,headers:hasBody?{"content-type":"application/json",...(options.headers||{})}:options.headers,body:hasBody?JSON.stringify(options.body):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error||"No se pudo completar la operación.");error.status=response.status;throw error}return payload}
function toast(message){const node=$("#productionToast");node.textContent=message;node.classList.add("show");setTimeout(()=>node.classList.remove("show"),2800)}
function today(){const parts=Object.fromEntries(new Intl.DateTimeFormat("en",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).map((part)=>[part.type,part.value]));return`${parts.year}-${parts.month}-${parts.day}`}
async function boot(){bind();$("#productionDate").value=today();try{const {operator}=await api("/api/production/me");await enter(operator)}catch{}}
function bind(){$("#productionLoginForm").addEventListener("submit",login);$("#toggleProductionPassword").addEventListener("click",()=>{const input=$("#productionPassword");input.type=input.type==="password"?"text":"password";$("#toggleProductionPassword").textContent=input.type==="password"?"Ver":"Ocultar"});$("#reloadProduction").addEventListener("click",load);$("#productionReportForm").addEventListener("submit",saveReport);$("#submitProductionReport").addEventListener("click",submitReport);$("#productionDate").addEventListener("change",renderReportForm);$("#addProductionExtra").addEventListener("click",addExtraProduct);$("#productionExtraCode").addEventListener("keydown",(event)=>{if(event.key==="Enter"){event.preventDefault();addExtraProduct()}});$("#productionReportItems").addEventListener("click",(event)=>{const remove=event.target.closest("[data-remove-extra]");if(remove){removeExtraProduct(Number(remove.dataset.removeExtra));return}const add=event.target.closest("[data-focus-extra]");if(add){$("#productionExtraProducts").scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>$("#productionExtraCode").focus(),300)}})}
async function login(event){event.preventDefault();const message=$("#productionLoginMessage");message.textContent="";try{const {operator}=await api("/api/production/login",{method:"POST",body:Object.fromEntries(new FormData(event.currentTarget))});await enter(operator)}catch(error){message.textContent=error.message}}
async function enter(operator){state.operator=operator;$("#productionLogin").classList.add("hidden");$("#productionWorkspace").classList.remove("hidden");$("#productionAdminPreview")?.classList.toggle("hidden",!operator.isAdmin);$("#productionSession").innerHTML=`<strong>${esc(operator.name)}</strong> <button id="productionLogout">Salir</button>`;$("#productionLogout").onclick=logout;await load()}
async function logout(){await api("/api/production/logout",{method:"POST"});location.reload()}
async function load(){const data=await api("/api/production/dashboard");state.plan=data.plan;state.reports=data.reports||[];state.operators=data.operators||[];state.products=data.products||[];renderPlan();renderReportForm();renderReports()}
function renderPlan(){const node=$("#productionPlan");const plan=state.plan;if(!plan){node.innerHTML=`<div class="report-card"><h2>No hay una planificación habilitada</h2><p>Administración todavía no aprobó el objetivo semanal.</p></div>`;return}const target=plan.items.reduce((sum,item)=>sum+item.targetQuantity,0);const produced=plan.items.reduce((sum,item)=>sum+item.producedQuantity,0);const extra=Number(plan.summary?.unplannedProducedQuantity||0);const remaining=Math.max(0,target-produced);const progress=target?Math.min(100,Math.round(produced*100/target)):0;const urgent=plan.items.filter((item)=>item.urgent&&item.remainingQuantity>0);node.innerHTML=`${urgent.length?`<div class="production-urgent-alert"><strong>⚠ PRODUCCIÓN URGENTE</strong><span>${urgent.map((item)=>`${esc(item.kmCode)}: ${item.remainingQuantity} u. pendientes · ${esc(item.latestAdditionReason||"Prioridad indicada por Administración")}`).join("<br>")}</span></div>`:""}<div class="plan-summary"><div class="stat"><span>Semana</span><strong>${formatDate(plan.weekStart)}</strong></div><div class="stat"><span>Objetivo</span><strong>${target}</strong></div><div class="stat"><span>Fabricado del plan</span><strong>${produced}</strong></div><div class="stat"><span>Pendiente</span><strong>${remaining}</strong></div></div><div class="plan-list">${plan.items.map((item)=>{const itemProgress=item.targetQuantity?Math.min(100,Math.round(item.producedQuantity*100/item.targetQuantity)):0;const progressState=itemProgress>=100?"complete":itemProgress>0?"active":"pending";const progressLabel=itemProgress>=100?"Objetivo completo":itemProgress>0?`${itemProgress}% fabricado`:"Sin producción confirmada";return `<article class="plan-item ${item.urgent?"is-urgent":""}"><div class="plan-item-head"><div><h3>${esc(item.kmCode)} · ${esc(item.name)}${item.urgent?'<span class="urgent-badge">URGENTE</span>':""}</h3>${item.addedQuantity?`<div class="added-plan-note"><strong>Agregado durante la semana: +${item.addedQuantity} u.</strong><span>Motivo: ${esc(item.latestAdditionReason||"Sin detalle adicional")}</span></div>`:""}<small>${item.warehouseLocation?`Ubicación: ${esc(item.warehouseLocation)}`:"Sin ubicación asignada"}</small></div><strong>${item.producedQuantity} / ${item.targetQuantity}</strong></div><div class="progress-meta"><span>${progressLabel}</span><strong>${itemProgress}%</strong></div><progress class="progress ${progressState}" aria-label="Avance de ${esc(item.kmCode)}" max="100" value="${itemProgress}">${itemProgress}%</progress><small>${item.remainingQuantity>0?`Faltan ${item.remainingQuantity} unidades`:"Objetivo semanal alcanzado"}</small></article>`}).join("")}</div><p class="help">Avance semanal: ${progress}%. Se actualiza cuando Administración confirma cada parte.${extra?` Producción adicional fuera del plan: ${extra} unidades.`:""}</p>`}
function reportContext(){const date=$("#productionDate").value||today();const existing=state.reports.find((report)=>report.productionDate===date);const planned=state.plan?.items||[];const plannedIds=new Set(planned.map((item)=>item.productId));let extraIds=state.extraProductsByDate.get(date);if(!extraIds){extraIds=new Set((existing?.items||[]).filter((item)=>!item.planItemId&&!plannedIds.has(item.productId)).map((item)=>item.productId));state.extraProductsByDate.set(date,extraIds)}return{date,existing,planned,plannedIds,extraIds,editable:!state.operator?.isAdmin&&(!existing||["draft","returned","submitted"].includes(existing.status))}}
function reportProduct(productId,existing){const catalog=state.products.find((product)=>product.id===productId);const saved=existing?.items?.find((item)=>item.productId===productId);return catalog||saved?{id:productId,kmCode:catalog?.kmCode||saved?.kmCode||"",name:catalog?.name||saved?.name||""}:null}
function renderReportItem(item,saved,editable,isExtra=false){return`<article class="report-item ${isExtra?"is-extra":""} ${item.urgent?"is-urgent":""}" data-report-product="${item.productId||item.id}"><div><strong>${esc(item.kmCode)}${isExtra?'<span class="extra-badge">Fuera del plan</span>':""}${item.urgent?'<span class="urgent-badge">URGENTE</span>':""}</strong><span>${esc(item.name)}</span>${item.addedQuantity?`<small class="added-plan-note"><strong>Agregado al plan: +${item.addedQuantity} u.</strong><span>Motivo: ${esc(item.latestAdditionReason||"Sin detalle adicional")}</span></small>`:""}<small>${isExtra?"Producción adicional; no modifica el avance del plan.":`Pendiente semanal: ${item.remainingQuantity}`}</small>${isExtra?`<label class="extra-reason">Motivo<input name="note-${item.productId||item.id}" list="productionExtraReasons" value="${esc(saved?.notes||"Aprovechamiento de sobrante")}" ${editable?"":"disabled"}></label>`:""}</div><label>Buenas<input name="good-${item.productId||item.id}" type="number" min="0" step="1" value="${saved?.goodQuantity||0}" ${editable?"":"disabled"}></label><label>Rechazadas<input name="rejected-${item.productId||item.id}" type="number" min="0" step="1" value="${saved?.rejectedQuantity||0}" ${editable?"":"disabled"}></label>${isExtra&&editable?`<button class="remove-extra" data-remove-extra="${item.productId||item.id}" type="button">Quitar</button>`:""}</article>`}
function captureReportDraft(date=$("#productionDate").value||today()){const form=$("#productionReportForm");if(!form||form.querySelectorAll("[data-report-product]").length===0)return;const items={};form.querySelectorAll("[data-report-product]").forEach((row)=>{const productId=Number(row.dataset.reportProduct);items[productId]={goodQuantity:Number(form.elements[`good-${productId}`]?.value||0),rejectedQuantity:Number(form.elements[`rejected-${productId}`]?.value||0),notes:form.elements[`note-${productId}`]?.value||""}});state.reportDraftByDate.set(date,{items,participantIds:[...form.querySelectorAll('input[name="participantIds"]:checked')].map((input)=>Number(input.value)),notes:form.elements.notes?.value||""})}
function renderReportForm(){const{date,existing,planned,extraIds,editable}=reportContext();const draft=state.reportDraftByDate.get(date);const savedFor=(productId)=>draft?.items?.[productId]||existing?.items?.find((row)=>row.productId===productId);state.draftId=existing?.id||null;const extra=[...extraIds].map((id)=>reportProduct(id,existing)).filter(Boolean);const rows=[...planned.map((item)=>renderReportItem(item,savedFor(item.productId),editable)),...extra.map((item)=>renderReportItem(item,savedFor(item.id),editable,true))];const addAnother=editable&&extra.length?`<button class="add-another-extra" data-focus-extra type="button">+ Agregar otro producto fuera del plan</button>`:"";$("#productionReportItems").innerHTML=rows.length?`<div class="report-items">${rows.join("")}${addAnother}</div>`:`<p>No hay productos cargados para este parte.</p>`;$("#productionExtraProducts").classList.toggle("hidden",!editable);$("#productionExtraCodes").innerHTML=state.products.filter((product)=>!planned.some((item)=>item.productId===product.id)&&!extraIds.has(product.id)).map((product)=>`<option value="${esc(product.kmCode)}">${esc(product.name)}</option>`).join("");$("#productionExtraCode").value="";$("#productionExtraMessage").textContent="";const selected=new Set(draft?.participantIds?.length?draft.participantIds:existing?.participantIds?.length?existing.participantIds:[state.operator?.id]);$("#productionReportParticipants").innerHTML=state.operators.map((operator)=>`<label><input name="participantIds" type="checkbox" value="${operator.id}" ${selected.has(operator.id)?"checked":""} ${editable?"":"disabled"}><span>${esc(operator.name)}</span></label>`).join("");$("#productionReportForm").elements.notes.value=draft?.notes??existing?.notes??"";$("#productionReportForm").elements.notes.disabled=!editable;$("#productionReportForm").querySelector('button[type="submit"]').disabled=!editable||!rows.length;$("#submitProductionReport").disabled=!existing||!editable||existing?.status==="submitted";$("#submitProductionReport").textContent=existing?.status==="submitted"?"Parte ya enviado":"Enviar a Administración";const message=$("#productionReportMessage");message.textContent=state.operator?.isAdmin?"Vista administrativa: la carga queda reservada a los operarios.":existing?.status==="submitted"?"Parte enviado. Si necesitás sumar otro producto, agregalo, guardá el borrador y volvé a enviarlo.":existing?statusText(existing):"";message.style.color=existing?.status==="returned"?"#ffb0b0":""}
function addExtraProduct(){const context=reportContext();const code=$("#productionExtraCode").value.trim().toUpperCase();const product=state.products.find((item)=>item.kmCode.toUpperCase()===code);const message=$("#productionExtraMessage");if(!product){message.textContent="No encontramos ese código KM.";return}if(context.plannedIds.has(product.id)){message.textContent="Ese producto ya forma parte de la planificación semanal.";return}if(context.extraIds.has(product.id)){message.textContent="Ese producto ya está agregado al parte.";return}captureReportDraft(context.date);context.extraIds.add(product.id);renderReportForm();$("#productionExtraMessage").textContent=`${product.kmCode} agregado. Podés cargar otro producto.`;$("#productionExtraMessage").classList.add("is-success");$("#productionExtraCode").focus();toast(`${product.kmCode} agregado fuera del plan.`)}
function removeExtraProduct(productId){const{date,extraIds}=reportContext();captureReportDraft(date);extraIds.delete(productId);state.extraProductsByDate.set(date,extraIds);const draft=state.reportDraftByDate.get(date);if(draft?.items)delete draft.items[productId];renderReportForm()}
async function saveReport(event){event.preventDefault();const form=event.currentTarget;const items=[...form.querySelectorAll("[data-report-product]")].map((row)=>{const productId=Number(row.dataset.reportProduct);return{productId,goodQuantity:Number(form.elements[`good-${productId}`].value||0),rejectedQuantity:Number(form.elements[`rejected-${productId}`].value||0),notes:form.elements[`note-${productId}`]?.value||""}}).filter((item)=>item.goodQuantity||item.rejectedQuantity);const participantIds=[...form.querySelectorAll('input[name="participantIds"]:checked')].map((input)=>Number(input.value));try{const productionDate=$("#productionDate").value;const {report}=await api("/api/production/reports",{method:"POST",body:{productionDate,notes:form.elements.notes.value,participantIds,items}});state.draftId=report.id;state.reportDraftByDate.delete(productionDate);toast("Borrador guardado.");await load()}catch(error){$("#productionReportMessage").textContent=error.message}}
async function submitReport(){if(!state.draftId)return;try{await api(`/api/production/reports/${state.draftId}/submit`,{method:"POST",body:{}});toast("Parte enviado a Administración.");await load()}catch(error){$("#productionReportMessage").textContent=error.message}}
function renderReports(){$("#productionReports").innerHTML=state.reports.length?state.reports.map((report)=>{const extras=report.items.filter((item)=>!item.planItemId);return`<article class="report-card"><div class="plan-item-head"><strong>${esc(report.reportNumber)} · ${formatDate(report.productionDate)}</strong><span class="status ${report.status}">${statusText(report)}</span></div><small>${report.items.reduce((sum,item)=>sum+item.goodQuantity,0)} buenas · ${report.items.reduce((sum,item)=>sum+item.rejectedQuantity,0)} rechazadas</small>${extras.length?`<small class="extra-summary">${extras.reduce((sum,item)=>sum+item.goodQuantity,0)} unidades fuera del plan</small>`:""}<small>Participaron: ${report.participants?.map((participant)=>esc(participant.name)).join(", ")||esc(report.operatorName)}</small>${report.status==="confirmed"?`<small>Comisión generada: $ ${Number(report.productionCommissionArs||0).toLocaleString("es-AR",{minimumFractionDigits:2})}</small>`:""}${report.returnReason?`<p>Corrección solicitada: ${esc(report.returnReason)}</p>`:""}</article>`}).join(""):`<p>Todavía no hay partes diarios.</p>`}
function statusText(report){return({draft:"Borrador",submitted:"Enviado, espera confirmación",confirmed:"Confirmado por Administración",returned:"Devuelto para corregir"})[report.status]||report.status}
function formatDate(value){if(!value)return"-";const [y,m,d]=value.split("-");return`${d}/${m}/${y}`}
boot();
loadNotificationCenter();

function loadNotificationCenter() {
  if (!document.querySelector('link[href*="notifications.css"]')) {
    const style = document.createElement("link");
    style.rel = "stylesheet";
    style.href = "/notifications.css?v=2";
    document.head.append(style);
  }
  if (!document.querySelector('script[src*="notifications.js"]')) {
    const script = document.createElement("script");
    script.src = "/notifications.js?v=3";
    script.defer = true;
    document.head.append(script);
  }
}
