const state={operator:null,plan:null,reports:[],operators:[],draftId:null};
const $=(s)=>document.querySelector(s);const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const hasBody=Object.prototype.hasOwnProperty.call(options,"body");const response=await fetch(path,{credentials:"same-origin",...options,headers:hasBody?{"content-type":"application/json",...(options.headers||{})}:options.headers,body:hasBody?JSON.stringify(options.body):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error||"No se pudo completar la operación.");error.status=response.status;throw error}return payload}
function toast(message){const node=$("#productionToast");node.textContent=message;node.classList.add("show");setTimeout(()=>node.classList.remove("show"),2800)}
function today(){const parts=Object.fromEntries(new Intl.DateTimeFormat("en",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).map((part)=>[part.type,part.value]));return`${parts.year}-${parts.month}-${parts.day}`}
async function boot(){bind();$("#productionDate").value=today();try{const {operator}=await api("/api/production/me");await enter(operator)}catch{}}
function bind(){$("#productionLoginForm").addEventListener("submit",login);$("#toggleProductionPassword").addEventListener("click",()=>{const input=$("#productionPassword");input.type=input.type==="password"?"text":"password";$("#toggleProductionPassword").textContent=input.type==="password"?"Ver":"Ocultar"});$("#reloadProduction").addEventListener("click",load);$("#productionReportForm").addEventListener("submit",saveReport);$("#submitProductionReport").addEventListener("click",submitReport);$("#productionDate").addEventListener("change",renderReportForm)}
async function login(event){event.preventDefault();const message=$("#productionLoginMessage");message.textContent="";try{const {operator}=await api("/api/production/login",{method:"POST",body:Object.fromEntries(new FormData(event.currentTarget))});await enter(operator)}catch(error){message.textContent=error.message}}
async function enter(operator){state.operator=operator;$("#productionLogin").classList.add("hidden");$("#productionWorkspace").classList.remove("hidden");$("#productionAdminPreview")?.classList.toggle("hidden",!operator.isAdmin);$("#productionSession").innerHTML=`<strong>${esc(operator.name)}</strong> <button id="productionLogout">Salir</button>`;$("#productionLogout").onclick=logout;await load()}
async function logout(){await api("/api/production/logout",{method:"POST"});location.reload()}
async function load(){const data=await api("/api/production/dashboard");state.plan=data.plan;state.reports=data.reports||[];state.operators=data.operators||[];renderPlan();renderReportForm();renderReports()}
function renderPlan(){const node=$("#productionPlan");const plan=state.plan;if(!plan){node.innerHTML=`<div class="report-card"><h2>No hay una planificación habilitada</h2><p>Administración todavía no aprobó el objetivo semanal.</p></div>`;return}const target=plan.items.reduce((sum,item)=>sum+item.targetQuantity,0);const produced=plan.items.reduce((sum,item)=>sum+item.producedQuantity,0);const remaining=Math.max(0,target-produced);const progress=target?Math.min(100,Math.round(produced*100/target)):0;node.innerHTML=`<div class="plan-summary"><div class="stat"><span>Semana</span><strong>${formatDate(plan.weekStart)}</strong></div><div class="stat"><span>Objetivo</span><strong>${target}</strong></div><div class="stat"><span>Fabricado</span><strong>${produced}</strong></div><div class="stat"><span>Pendiente</span><strong>${remaining}</strong></div></div><div class="plan-list">${plan.items.map((item)=>{const itemProgress=item.targetQuantity?Math.min(100,Math.round(item.producedQuantity*100/item.targetQuantity)):0;const progressState=itemProgress>=100?"complete":itemProgress>0?"active":"pending";const progressLabel=itemProgress>=100?"Objetivo completo":itemProgress>0?`${itemProgress}% fabricado`:"Sin producción confirmada";return `<article class="plan-item"><div class="plan-item-head"><div><h3>${esc(item.kmCode)} · ${esc(item.name)}</h3><small>${item.warehouseLocation?`Ubicación: ${esc(item.warehouseLocation)}`:"Sin ubicación asignada"}</small></div><strong>${item.producedQuantity} / ${item.targetQuantity}</strong></div><div class="progress-meta"><span>${progressLabel}</span><strong>${itemProgress}%</strong></div><div class="progress ${progressState}" role="progressbar" aria-label="Avance de ${esc(item.kmCode)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${itemProgress}"><span style="width:${itemProgress}%"></span></div><small>${item.remainingQuantity>0?`Faltan ${item.remainingQuantity} unidades`:"Objetivo semanal alcanzado"}</small></article>`}).join("")}</div><p class="help">Avance semanal: ${progress}%. Se actualiza cuando Administración confirma cada parte.</p>`}
function renderReportForm(){const date=$("#productionDate").value||today();const existing=state.reports.find((report)=>report.productionDate===date);state.draftId=existing?.id||null;const editable=!state.operator?.isAdmin&&(!existing||["draft","returned"].includes(existing.status));const products=state.plan?.items||[];$("#productionReportItems").innerHTML=products.length?`<div class="report-items">${products.map((item)=>{const saved=existing?.items?.find((row)=>row.productId===item.productId);return `<article class="report-item"><div><strong>${esc(item.kmCode)}</strong><span>${esc(item.name)}</span><small>Pendiente semanal: ${item.remainingQuantity}</small></div><label>Buenas<input name="good-${item.productId}" type="number" min="0" step="1" value="${saved?.goodQuantity||0}" ${editable?"":"disabled"}></label><label>Rechazadas<input name="rejected-${item.productId}" type="number" min="0" step="1" value="${saved?.rejectedQuantity||0}" ${editable?"":"disabled"}></label></article>`}).join("")}</div>`:`<p>No hay productos en un plan aprobado.</p>`;const selected=new Set(existing?.participantIds?.length?existing.participantIds:[state.operator?.id]);$("#productionReportParticipants").innerHTML=state.operators.map((operator)=>`<label><input name="participantIds" type="checkbox" value="${operator.id}" ${selected.has(operator.id)?"checked":""} ${editable?"":"disabled"}><span>${esc(operator.name)}</span></label>`).join("");$("#productionReportForm").elements.notes.value=existing?.notes||"";$("#productionReportForm").elements.notes.disabled=!editable;$("#productionReportForm").querySelector('button[type="submit"]').disabled=!editable||!products.length;$("#submitProductionReport").disabled=!existing||!editable;const message=$("#productionReportMessage");message.textContent=state.operator?.isAdmin?"Vista administrativa: la carga queda reservada a los operarios.":existing?statusText(existing):"";message.style.color=existing?.status==="returned"?"#ffb0b0":""}
async function saveReport(event){event.preventDefault();const form=event.currentTarget;const items=(state.plan?.items||[]).map((item)=>({productId:item.productId,goodQuantity:Number(form.elements[`good-${item.productId}`].value||0),rejectedQuantity:Number(form.elements[`rejected-${item.productId}`].value||0)})).filter((item)=>item.goodQuantity||item.rejectedQuantity);const participantIds=[...form.querySelectorAll('input[name="participantIds"]:checked')].map((input)=>Number(input.value));try{const {report}=await api("/api/production/reports",{method:"POST",body:{productionDate:$("#productionDate").value,notes:form.elements.notes.value,participantIds,items}});state.draftId=report.id;toast("Borrador guardado.");await load()}catch(error){$("#productionReportMessage").textContent=error.message}}
async function submitReport(){if(!state.draftId)return;try{await api(`/api/production/reports/${state.draftId}/submit`,{method:"POST",body:{}});toast("Parte enviado a Administración.");await load()}catch(error){$("#productionReportMessage").textContent=error.message}}
function renderReports(){$("#productionReports").innerHTML=state.reports.length?state.reports.map((report)=>`<article class="report-card"><div class="plan-item-head"><strong>${esc(report.reportNumber)} · ${formatDate(report.productionDate)}</strong><span class="status ${report.status}">${statusText(report)}</span></div><small>${report.items.reduce((sum,item)=>sum+item.goodQuantity,0)} buenas · ${report.items.reduce((sum,item)=>sum+item.rejectedQuantity,0)} rechazadas</small><small>Participaron: ${report.participants?.map((participant)=>esc(participant.name)).join(", ")||esc(report.operatorName)}</small>${report.status==="confirmed"?`<small>Comisión generada: $ ${Number(report.productionCommissionArs||0).toLocaleString("es-AR",{minimumFractionDigits:2})}</small>`:""}${report.returnReason?`<p>Corrección solicitada: ${esc(report.returnReason)}</p>`:""}</article>`).join(""):`<p>Todavía no hay partes diarios.</p>`}
function statusText(report){return({draft:"Borrador",submitted:"Enviado, espera confirmación",confirmed:"Confirmado por Administración",returned:"Devuelto para corregir"})[report.status]||report.status}
function formatDate(value){if(!value)return"-";const [y,m,d]=value.split("-");return`${d}/${m}/${y}`}boot();
