const root=document.querySelector("#remitRoot");
const orderId=Number(new URLSearchParams(location.search).get("order")||0);
const returnUrl=`./logistica.html?order=${orderId}`;
const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS"});
init();

async function init(){
  if(!orderId)return error("Falta el pedido para generar el remito.");
  try{const response=await fetch(`/api/logistics/orders/${orderId}/shipping-remit`);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No se pudo generar el remito.");render(payload)}catch(e){error(e.message)}
}
function render({order,generatedAt}){
  root.innerHTML=`<div class="screen-actions"><a href="${returnUrl}">Volver al pedido ${esc(order.orderNumber)}</a><strong>${esc(order.orderNumber)} · ${order.packages} bulto${order.packages===1?"":"s"}</strong><button id="printRemit">Imprimir remito A4 por duplicado</button></div>${copy(order,generatedAt,"ORIGINAL · TRANSPORTE / DESTINATARIO")}${copy(order,generatedAt,"DUPLICADO · KM DETAIL LINE")}`;
  document.querySelector("#printRemit").addEventListener("click",()=>print());
}
function copy(o,date,label){const s=o.shipping||{};const destination=[s.address,s.city,s.province,s.postalCode?`CP ${s.postalCode}`:""].filter(Boolean).join(" · ");const transport=s.preferredTransport||o.fulfillment?.carrier||o.fulfillment?.method||"A coordinar";return `<section class="remit-sheet"><header><div class="brand"><img src="./assets/km-metal-logo.png" alt="KM Detail Line"><div><p>Documento de envío · No fiscal</p><h1>Remito de envío</h1></div></div><div class="number"><span>${esc(label)}</span><strong>${esc(o.remitNumber)}</strong><small>${formatDate(date)}</small></div></header><div class="copy-label">${esc(label)}</div><section class="meta"><div><span>Origen</span><strong>KM Detail Line</strong><small>Rosario, Santa Fe · CUIT 27-28000765-5</small></div><div><span>Destinatario</span><strong>${esc(o.businessName)}</strong><small>${esc(o.contactPerson||s.recipient||"")}</small></div><div><span>Domicilio de entrega</span><strong>${esc(destination||"A coordinar")}</strong><small>${esc([s.contactPhone,o.customerWhatsapp].filter(Boolean).join(" · "))}</small></div><div><span>Transporte / modalidad</span><strong>${esc(transport)}</strong><small>Pedido ${esc(o.orderNumber)}</small></div></section><table><thead><tr><th>Código</th><th>Producto</th><th class="qty">Cantidad</th></tr></thead><tbody>${o.items.map(i=>`<tr><td><strong>${esc(i.kmCode)}</strong><small>EAN ${esc(i.ean13||"-")}</small></td><td>${esc(i.productName)}</td><td class="qty"><strong>${i.quantity}</strong></td></tr>`).join("")}</tbody></table><section class="summary"><div><span>Total de bultos</span><strong>${o.packages}</strong></div><div><span>Valor declarado</span><strong>${money.format(o.declaredValueCents/100)}</strong><small>Valor declarado para transporte</small></div></section><section class="signatures"><div><span>Entregado por</span><i></i><small>Firma y aclaración</small></div><div><span>Recibido por</span><i></i><small>Firma, aclaración y DNI</small></div><div><span>Fecha y hora</span><i></i><small>Constancia de recepción</small></div></section><footer>Este documento acompaña el envío y no reemplaza la factura ni otro comprobante fiscal.</footer></section>`}
function formatDate(v){return new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
function error(message){root.innerHTML=`<section class="screen-panel"><h1>No se pudo generar el remito</h1><p>${esc(message)}</p><a href="${returnUrl}">Volver al pedido</a></section>`}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
